

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

bridge:
    resource: "@BridgeBundle/Resources/config/routing.yml"
    prefix:   /

writer:
    resource: "@WriterBundle/Resources/config/routing.yml"
    prefix:   /

mailer:
    resource: "@MailerBundle/Resources/config/routing.yml"
    prefix:   /


zma_forum:
    resource: "@ZMAForumBundle/Resources/config/routing.yml"
    prefix:   /forum

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/Config/routing/security.xml"

fos_use_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_use_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_use_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_use_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile