services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\Antispam
        arguments:
            - "@mailer"
            - "%locale%"
            - 50

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationEmailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }